# Generated by Django 5.2.4 on 2025-07-15 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_follow_userprofile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='crated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Desde cuando lo sigue?'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folloer_set', to='profiles.userprofile', verbose_name='Quien sigue?'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to='profiles.userprofile', verbose_name='A quien sigue?'),
        ),
    ]
