# Generated by Django 5.2.4 on 2025-07-16 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_follow_crated_at_alter_follow_follower_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to='profiles.userprofile', verbose_name='Quien sigue?'),
        ),
    ]
